# try:
#     print('try')
# except:
#     print('default except')
# except ArithmeticError as e:
#     print('except')

# SyntaxError: default 'except:' must be last
