try:
    print('try')
except:
    print('except')
try:
    print('try')
except:
    print('except')

# This is valid
# output:
# try
# try

