try:
    print('try')
    # try:
    #     print('inner try')
except:
    print('except')
finally:
    print('finally')

# This is Invalid
# Taking inner try without except or finally



